### ISSUE TITLE
-- is not supported

### ISSUE THREAD

**Issue by emanuele6** [curl/trurl#102]
`trurl` doesn't support the standard `--` argument to indicate end of options

```
bash-5.1$ trurl --
trurl error: unknown option: --
trurl error: Try trurl -h for help
bash-5.1$ trurl -- hi
trurl error: unknown option: --
trurl error: Try trurl -h for help
```

**Comment by bagder** [comment]
What are you proposing it should do?

**Comment by emanuele6** [comment]
It should work like in other tools, it should be ignored, and arguments after it should not be treated as options even if they start with `-`.

Currenlty it is not possible to pass arguments that start with `-`, and also if a user blindly passes arguments to `trurl`, some of those arguments could be unintentionally interpreted as options:

```bash
#!/bin/bash --
urls=( example.org --json emanuele6:hunter2@github.com ) # got from somewhere, e.g. "$@"
trurl -s scheme=https "${urls[@]}"
```
Output:
```json
[
  {
    "url": "https://example.org/",
    "scheme": "https",
    "host": "example.org",
    "port": "443",
    "path": "/"
  },
  {
    "url": "https://emanuele6:hunter2@github.com/",
    "scheme": "https",
    "user": "emanuele6",
    "password": "hunter2",
    "host": "sdf.org",
    "port": "443",
    "path": "/"
  }
]
```
Instead of the expected:
```
https://example.org/
https://--json/
https://emanuele6:hunter2@github.com/
```

`trurl -s scheme=https -- "${urls[@]}"` would fix this problem.
