### ISSUE TITLE
CI job to verify build on Windows

### ISSUE THREAD

**Issue by bagder** [curl/trurl#109]
- [ ] merge a Windows capable build (makefile?)
 - [ ] add a CI job that verifies that trurl builds and works fine on Windows

**Comment by havbon** [comment]
I added another job in the makefile.yml
have a look: https://github.com/havbon/trurl/actions

I got it to work using cygwin's gcc compiler without changing the makefile at all.

In my opinion that is the best way to compile trurl on windows

**Comment by havbon** [comment]
The main issue is find is that it is difficult to find libcurl packages for windows which includes both ".lib" files and "curl.h", which is needed for the msvc compiler...

Any idea where to find that?

**Comment by jay** [comment]
note @krishean is working on this in #110

**Comment by jacobmealey** [comment]
Is this issue still applicable with the merging of #110?

**Comment by vszakats** [comment]
Conceptually, this could use the ready-made official curl binaries from https://curl.se/windows.
Then pick a suitable mingw-w64 toolchain, and build trurl with them. This would duplicate
some of what curl-for-win does already. To make maintenance bearable (i.e. avoid maintaining
two copies of the same logic), using llvm-mingw seems to be the best option, as it has most of
the necessary options configured out of the box, and also supports all CPUs and other bits.

Another approach is to download the curl-for-win repo, configure for 'pico' (smallest) build
and let it build trurl automatically (along with curl itself). That would require just a tiny amount
of extra code to maintain.

**Comment by vszakats** [comment]
PR with the second approach outlined above: #249
