### ISSUE TITLE
Should `{query:}` be case sensitive?

### ISSUE THREAD

**Issue by xfgusta** [curl/trurl#118]
Currently, the `{component}` is case insensitive

```
$ trurl "https://duck.com/?q=trurl&t=h_&ia=web" --get "{query}\n{QUERY}"
q=trurl&t=h_&ia=web
q=trurl&t=h_&ia=web
```

But `{query:}` isn't, which seems inconsistent

```
$ trurl "https://duck.com/?q=trurl&t=h_&ia=web" --get "{query:q}\n{QUERY:q}"
trurl
trurl error: Bad --get syntax: QUERY:q}
trurl error: Try trurl -h for help
```

**Comment by jacobmealey** [comment]
it seems like perhaps `{component}` should be case-sensitive. The help page gives no indication that it's case-insensitive. I think it's case insensitive on purpose but I think it might be beneficial to limit these types of things to lowercase to mitigate future inconsistencies like this.

**Comment by bagder** [comment]
I think `{query}` might as well always be lowercase. I'll fix.
