### ISSUE TITLE
Issues with --get on windows powershell

### ISSUE THREAD

**Issue by havbon** [curl/trurl#129]
There seems to be some issues when using --get on windows, here is the log from test.py
[testout.log](https://github.com/curl/trurl/files/11201260/testout.log)

When executing `--get {url}` it outputs `url`

**Comment by bagder** [comment]
That's because it's not quoted isn't it?

**Comment by havbon** [comment]
![image](https://user-images.githubusercontent.com/46850782/231225781-1e960611-b573-4d24-b58a-aa427f45bc3c.png)

i'm afraid not, ill do some more testing in a bit

**Comment by havbon** [comment]
a few more examples:
![image](https://user-images.githubusercontent.com/46850782/231243640-344509e9-5339-4fc7-81c4-9f6f8ec4703b.png)


It probably has something to do with:

> To create or display a variable name that includes spaces or special characters, enclose the variable name with the curly braces ({}) characters. The curly braces direct PowerShell to interpret the variable name's characters as literals.

from [powershell docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_variables?view=powershell-7.3)

But it's difficult to tell...

**Comment by emanuele6** [comment]
I can't reproduce this on powershell on linux:
```
PowerShell 7.3.3
PS /home/emanuele6> trurl localhost -g {host}
trurl error: unknown option: -inputFormat
trurl error: Try trurl -h for help
PS /home/emanuele6> trurl localhost -g '{host}'
localhost
PS /home/emanuele6> trurl localhost -g "{host}"
localhost
PS /home/emanuele6>
```

`{host}` does not expand if you use quote it either using `"` or `'`. It only expands when not quoted as described by the documentation.

<https://learn.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-170>
IIRC, on Windows, processes are created with one single argument, not with a vector or multiple arguments (`argv`) like in UNIX systems.  And how the quoting is interepreted/wildcards/etc of the single argument are interpreted is up to the individual process; in the case of C programs with a main() function, how the quoting is handled is decided by the startup code that calls main added by the linker/compiler.

Maybe check the documentation of the build tools you used to compile to `trurl` on Windows to see if you can find how `{host}` should be quoted, or any other information about this.

**Comment by emanuele6** [comment]
Maybe your trurl.exe understands that `-encodedCommand` stuff.
Can you try to see if `.\trurl.exe localhost -g {{host}}` works for you? (it should expand to that stuff with `{host}` base64 encoded)

**Comment by bagder** [comment]
If we assume for a moment that PowerShell is this brain dead, should we consider supporting another marker around the variable names maybe in addition to `{}` to make it easier for PowerShell users? Like maybe `[]`?

**Comment by havbon** [comment]
@emanuele6 
![image](https://user-images.githubusercontent.com/46850782/231469810-bca2568a-0d4a-42ea-a3dc-3d4ef07516c7.png)

@bagder 
I tried to add the changes you talked about and it actually did work...
![image](https://user-images.githubusercontent.com/46850782/231472174-e49ba873-7dd6-4b12-b1ba-54cb99db1450.png)

**Comment by havbon** [comment]
For some reason it does work when Theres a space between } and ". Maybe as a workaround we could just add that space automatically?

**Comment by havbon** [comment]
You are completely right, adding alternative to '{}' is probably the best option then

**Comment by emanuele6** [comment]
I borrowed a Windows PC with powershell to test this.

It seems that for some reason `'{foo}'` is basically equivalent to `{foo}` on Windows's powershell unlike on Linux.

I have noticed that "escaping" the `'{foo}'` either with `\'{foo}'` or with `'\{foo}'` makes it work properly and just pass "{foo}" as is to trurl.
```
PS C:\Users\XXX\trurl> .\trurl.exe gopher://localhost -g '{scheme}'
scheme
PS C:\Users\XXX\trurl> .\trurl.exe gopher://localhost -g \'{scheme}'
gopher
PS C:\Users\XXX\trurl> .\trurl.exe gopher://localhost -g '\{scheme}'
gopher
```

So that is one way to make `-g '{host}'` work on Windows's powershell, but I am not sure that is a good option.

This is a special case for `'{foo}'` apparently, in `'hi \{scheme}'` and `\'hi {scheme}'`, the backslash is literal:
```
PS C:\Users\XXX\trurl> .\trurl.exe gopher://localhost -g \'hi {scheme}'
\hi gopher
PS C:\Users\XXX\trurl> .\trurl.exe gopher://localhost -g 'hi \{scheme}'
hi \{scheme}
PS C:\Users\XXX\trurl> .\trurl.exe gopher://localhost -g '\hi {scheme}'
\hi gopher
```

And it is also specific to the powershell shipped with Windows: on Linux powershell, `'\{scheme}'` contains a literal backslash, and `'{scheme}'` works correctly as I mentioned previously.

Maybe this was an old bug that has been fixed, many powershell versions ago.
The PC on which I tested this was an old Surface tablet laptop that originally had Windows 8.1 Pro, and was later updated to Windows 10, and it is using powershell version `5.1.x`.
```
PS C:\Users\XXX\trurl> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

On Linux, I have used powershell 7.3.3 that is the latest version \(excluding version 7.3.4 that was just released [5 hours ago](https://github.com/PowerShell/PowerShell/releases)\).

@havbon What version of Windows are you using? And what does `$PSVersionTable` output for you?

If you are not using Windows 11, maybe this issue does not occur on Windows 11's powershell.

**Comment by bagder** [comment]
Does #133 make it more comfortable to use with PowerShell?

With that, you can instead opt to use `[host]` etc.

**Comment by havbon** [comment]
@emanuele6 

```
PS C:\Users\Håvard\git\trurl> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\Users\Håvard\git\trurl>
```

windows details:

Edition	Windows 11 Home
Version	22H2
Installed on	‎2/‎22/‎2023
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0

**Comment by havbon** [comment]
> Does #133 make it more comfortable to use with PowerShell?
> 
> With that, you can instead opt to use `[host]` etc.

```
PS C:\Users\Håvard\git\trurl> .\trurl.exe localhost -g "{host}"
host
PS C:\Users\Håvard\git\trurl> .\trurl.exe localhost -g "[host]"
localhost
```

It does work when using `[]`

**Comment by bagder** [comment]
Since d2f461a56491e953ce806 trurl also supports [brackets] for variables.
