### ISSUE TITLE
test.py does not return error on failures, does not verify `stderr`

### ISSUE THREAD

**Issue by bagder** [curl/trurl#140]
It should return a non-zero exit code to make CI builds etc report errors proper.

`tests.json` includes a `stderr` for all tests but test.py does not verify this data?

/cc @havbon

**Comment by havbon** [comment]
stderr was intentionally disabled because of a comment from the original issue.

> When it comes to errors, the more important part is the exit code so maybe we should start with verifying that only and save stderr checking for later.

But I enabled it and fixed the exit code.
