### ISSUE TITLE
adapt tests to less capable libcurl versions

### ISSUE THREAD

**Issue by bagder** [curl/trurl#150]
- trurl can get **built** with a restricted libcurl
- trurl might **execute** with a restricted libcurl

(where "restricted" means it might not have all the features or might suffer from a known bug.)

These needs to be taken into account when running tests, since not all features can evaluate and be performed in all situations.

**Comment by bagder** [comment]
One way we could do it:

1. provide a command line option to trurl that outputs its limitations in a list
2. make tests that require a special feature to be marked accordingly
3. have the test runner skip the tests in (2) for which (1) says can't be run.

**Comment by krishean** [comment]
I have a potential solution to this for the python script, I'll put in a request when I get back to my computer.

It adds a "minversion" attribute to the relevant tests in tests.json, and gets the libcurl version from the trurl version string on starting the script.

**Comment by bagder** [comment]
> It adds a "minversion" attribute to the relevant tests in tests.json, and gets the libcurl version from the trurl version string on starting the script.

That can work. At least if we also provide information about which libcurl version that was used when trurl was *built*  - some functionality are limited by built-time conditions and some by run-time.

**Comment by bagder** [comment]
I made #156 to help.

**Comment by krishean** [comment]
Would we need two minversion attributes in the json then, one for build-time and another for run-time? That would be easy enough with something like "minruntime" and "minbuildtime".

Or would one minversion attribute be checked against both verions?

**Comment by krishean** [comment]
Have a look at: https://github.com/krishean/trurl/tree/built-version, if it's what you're looking for I'll open a request.

Otherwise I can change it if needed.

**Comment by havbon** [comment]
Another thing to consider is that some tests will fail on Windows builds, because of the `{}` issues. We should adapt Windows tests accordingly. Find a way to exclude those tests on Windows for example

**Comment by havbon** [comment]
essentially `.\trurl.exe localhost --get '{host}'` just returns `host`.
see #129

**Comment by bagder** [comment]
> I know the "--accept-space" tests require version 7.78.0 or above, but I'm unsure if that's a run-time or build-time dependency

It's a build-time requirement, but then it also does not work for earlier run-times either.

**Comment by bagder** [comment]
> I've also noticed a couple of the tests with ipv6 addresses fail on ubuntu

See `URL-QUIRKS.md`. That's the "Normalizing IPv6 addresses" in 7.81.0, a run-time req.

**Comment by bagder** [comment]
> Another thing to consider is that some tests will fail on Windows builds

I consider that a separate issue. Also: "I have all the tests passing on windows" makes it more complicated than just "on Windows". Is it because of running in powershell vs otherwise?
