### ISSUE TITLE
Trurl act as a filter

### ISSUE THREAD

**Issue by jacobmealey** [curl/trurl#159]
It may be beneficial to have the ability to filter URLs based on a set of criteria.
I was thinking something like `cat url-list.txt | trurl --url-file - --filter "host=example.com scheme=ftp"` and trurl would only print the URLs which match the criteria.

**Comment by emanuele6** [comment]
You could use `jq` for this since `trurl` flushes after every URL is handled:

```bash
cat url-list.txt | # or command that generates URLs
# parse URLs with trurl
trurl --json -f - |
# filter them with jq
jq --stream -n '
    # extracts elements from the array
    fromstream(1 | truncate_stream(inputs)) |
    # filter out URLs with host!="example.org" and scheme!="ftp"
    select(.host == "example.org" and .scheme == "ftp)
    # output the url
    .url
'
```

Example:
```bash
printf %s\\n https://curl.se/trurl ftp://example.org/baz \
             ftp://curl.se/curl http://example.org/hi \
             ftp://emanuele6:hunter2@example.org/foo |
trurl --json -f - |
jq --stream -rn '
    fromstream(1 | truncate_stream(inputs)) |
    select(.host == "example.org" and .scheme == "ftp).url
'
# Output:
#  ftp://example.org/baz
#  ftp://emanuele6:hunter2@example.org/foo
```

If you don't care about the the filter outputting results immediately, or you can wait for trurl to output the entire JSON array (e.g. when reading URLs from a txt file instead of the output of a command), you can also just use:
```bash
trurl --json -f url-file.txt |
jq 'select(.host == "example.org" and .scheme == "ftp").url'
```

**Comment by jacobmealey** [comment]
That is trickier than I was originally thinking. @emanuele6 solution is good enough for folks who would need something like this.

**Comment by bagder** [comment]
Right, or even anything else
~~~
trurl -f file -g '{url} {host}' | ./filter
~~~

The `filter` script then checks the second argument for whatever and it matches, outputs the first argument. Could easily be written in awk, perl, python, bash or whatever you prefer.

**Comment by jacobmealey** [comment]
Alright, then perhaps we should close this issue, and if somebody has a _really_ compelling reason to implement directly in trurl then we can reopen it.
