### ISSUE TITLE
unable to selectively remove query parameters with asterisk in them

### ISSUE THREAD

**Issue by schuelermine** [curl/trurl#227]
Query parameters containing the `*` character cannot be effectively targeted as the wildcard matches other parameters as well. I suggest identifying `%2a` with `*`, which currently would only match a literal `%2a` in the original URI, as a workaround.

**Comment by bagder** [comment]
Browsers don't follow RFC 3986, they do [their own thing](https://url.spec.whatwg.org/).

> I suggest identifying %2a with *, which currently would only match a literal %2a in the original URI, as a workaround.

I don't follow. Can you show with an example use case what you mean?

**Comment by schuelermine** [comment]
I mean removing `*=0` when `%2a` is requested to be removed.

**Comment by bagder** [comment]
Supporting `%2a` for that seems a little weird unless we support the entire thing percent encoded, but then that might be odd as well.

What if we just allow backslash escaping, the way it is a little more traditionally done? Like: `--trim 'query=\*'` ?

**Comment by bagder** [comment]
Actually, a quirky work-around that already works is this: `--trim 'query=**'` since it will make a match of all queries that begin with `*`...

**Comment by jacobmealey** [comment]
> What if we just allow backslash escaping, the way it is a little more traditionally done? Like: --trim 'query=\*' ?

this seems like the most intuitive approach -- I don't think I ever would have tried `query=**` to solve this.
