### ISSUE TITLE
About the release scheme

### ISSUE THREAD

**Issue by chenrui333** [curl/trurl#245]
👋 It looks like all the releases are marked pre-release, is there any docs for it? It would be good that the releases are marked as stable release, so that pre-release label can be used for pre-release purposes. Thanks!

 (side note, we, homebrew, are using the release API to distinguish the stable release vs pre-release)

relates to https://github.com/Homebrew/homebrew-core/pull/152930

**Comment by bagder** [comment]
There is no real docs about it, no. Only some spotty mentions in random places:

I wanted to do pre-releases for a while to allow us to experiment with options, style and syntax before we feel that we can carve them into stone and stick to them for a long time forward.

As I believe we have not felt a need to do any major changes recently and things are progressing pretty good in the style we have established, I want to do a proper 1.0 release "soon". Maybe we should just set a date in a few weeks, allow for a little time for people to test and verify the latest - and then ship a 1.0.

**Comment by chenrui333** [comment]
Totally, it is just more of sentiment thing.

For now, we are just gonna ship the pre-releases then. (to me, if the current latest release works for you, I personally it might be a good thing to promote it to `latest release`, that implies `stable` sentiment, but not exactly the same as stable release based on my observations :) but your call)

**Comment by bagder** [comment]
Ok, I toggled off the pre-release here now to make it show up as latest release proper. I still intend to do a 1.0 soonish.

**Comment by vszakats** [comment]
While adding trurl support to curl-for-win, I noticed that the published 0.9 tarball returns version 0.8. I reckon it's a recurring issue with tagged source tarballs. Perhaps something to tackle for 1.0.

**Comment by bagder** [comment]
Yeah, [I noticed](https://github.com/curl/trurl/discussions/244#discussioncomment-7436369) as well, and now I have created and added a RELEASE-PROCEDURE document with a checklist that hopefully should help me avoid this mistake next time.

**Comment by chenrui333** [comment]
Thanks @bagder! I think I have got what I need for this thread. Closing the issue now.
