### ISSUE TITLE
Date in manpage is out of sync with commit/release date

### ISSUE THREAD

**Issue by gnomon-** [curl/trurl#315]
In `trurl.1`, as of commit 0942de3c17a027e14108dc9177fbebd11a651f82, the man page specifies that the date of the manual is 2023-04-27:

```
$ grep -E '^\.TH trurl 1' trurl.1
.TH trurl 1 "April 27, 2023" "trurl" "trurl Manual"
```

It could be possible to add a step in the Makefile that updates this value as necessary to match the date of the repo commit at compilation time, e.g. with something like:

```bash
git log -n1 HEAD --date=format:'%B %d, %Y' --pretty=format:'%ad'
```

...which for that same aforementioned commit would yield..:

```
July 29, 2024
```

I also find it useful that the `git.1` man page includes the release version in it, which lets me quickly check if the version I have compiled and installed from source is the one I expected, but the extra complication required to achieve this might not be worth the trouble.

**Comment by bagder** [comment]
Fair. It is time to create a script to run at release time to fixup the files as necessary: the date/version in `trurl.1` and the version in `version.h`.

**Comment by gnomon-** [comment]
You are a gentleman and a scholar, sir.
