### ISSUE TITLE
--replace doesn't urlencode values

### ISSUE THREAD

**Issue by gromnitsky** [curl/trurl#321]
~~~
$ trurl 'example.com/?q=x#bar' --replace q='#x'
http://example.com/?q=#x#bar
~~~

I thought it would print `http://example.com/?q=%23x#bar`.

**Comment by emanuele6** [comment]
`--force-replace` and `--trim query=` have similar bugs:
```
$ trurl --force-replace a%=z 'https://example.com/'
trurl note: key 'a%' not in url, appending to query
https://example.com/?a%=z
$ trurl --trim query=a% 'https://example.com/?a%25'
https://example.com/?a%25
$ trurl --trim query=a%25 'https://example.com/?a%25'
https://example.com/
```

**Comment by jacobmealey** [comment]
I propose we add `:` modifier to trim so you could do:
```
$ trurl --trim query=a% 'https://example.com/?a%25'
https://example.com/
$ trurl --trum query:=a%25  'https://example.com/?a%25'
https://example.com/
```
I'm not sure how we would handle it for replace. any ideas?

**Comment by emanuele6** [comment]
> I'm not sure how we would handle it for replace. any ideas?

`--replace`/`--force-replace` can just work like `--append query=` that does not have the bug.

> I propose we add `:` modifier to trim so you could do:

Not a fan. Anyway moving to a separate issue
