### ISSUE TITLE
`--trim` checks query keys literally ignoring URL encoding

### ISSUE THREAD

**Issue by emanuele6** [curl/trurl#326]
Consider the following url that has three query parameters that start with "a": `a1`, `a2`, `a3`
```
https://example.com/?%611&a2&a3
```
`--trim 'query=a*'` will only remove `a2`, and `a3` because `a1` is written as `%611` and `--trim` compares keys literally
```console
$ trurl --trim 'query=a*' 'https://example.com/?%611&a2&a3'
https://example.com/?%611
```
Additionally, as mentioned in #321, this also causes `--trim query=%`/`--trim query=%25` to have surprising behaviour
```console
$ trurl --trim query=a% 'https://example.com/?a%25'
https://example.com/?a%25
$ trurl --trim query=a%25 'https://example.com/?a%25'
https://example.com/
```

Clearly `--trim` with `a*` should trim both `%611` and `a2`, and not check literally.

And `--trim query=a%` should either delete a key equal to `a%`, or be invalid; and `--trim query=a%25` should either delete a key equal to `a%25`, or a key equal to `a%`.
Personally, I prefer the second option because that would allow implementing `--trim 'query=%2a*` as a way to trim keys that start with "\*".

**Comment by bagder** [comment]
Related:
~~~
$ trurl 'https://ex%61mple.com/p%61th/?%611&a2&a3' 
https://example.com/p%61th/?%611&a2&a3
~~~

This normalizes the hostname part where %61 becomes 'a' but not in the path and query...
