### ISSUE TITLE
Errors in auto generated manpage

### ISSUE THREAD

**Issue by abbbi** [curl/trurl#347]
hi,

the debian linter checks for issues in manpages too, it seems the new generated manapge from MD format
has some syntax issues. You can test with:

https://curl.se/trurl/trurl.1

..
```
LC_ALL=C.UTF-8 MANROFFSEQ='' MANWIDTH=80  man --warnings -E UTF-8 -l -Tutf8 -Z  ./trurl.1 > /dev/null
troff: <standard input>:233: warning: macro '\' not defined
```

the section in the TH field seems to be off too (its the trurl version, not the section of the manual page)

`.TH trurl 0.15 1 "2024-08-27" trurl`

should be

`.TH trurl 1 "2024-08-27" trurl 0.15`

i guess.

**Comment by bagder** [comment]
I'll have a look and fix
