### ISSUE TITLE
Unexpected repetition of params with empty query parameters

### ISSUE THREAD

**Issue by schpet** [curl/trurl#351]
it's not clear to me if this is my ignorant understanding of urls or a bug with trurl, but when i pass an empty query parameter it seems to have a problem where it repeats query params:

```bash
trurl --url "http://example.com/?a=&b=1" --json
```

```json
[
  {
    "url": "http://example.com/?a=%26b%3d1&b=1",
    "parts": {
      "scheme": "http",
      "host": "example.com",
      "path": "/",
      "query": "a=&b=1&b=1"
    },
    "params": [
      {
        "key": "a",
        "value": ""
      },
      {
        "key": "b",
        "value": "1"
      }
    ]
  }
]
```

```bash
trurl --version
trurl version 0.15 libcurl/8.7.1 [built-with 8.4.0]
features: imap-options normalize-ipv4 url-strerror white-space zone-id
```

<img width="575" alt="screenshot showing same code as described above" src="https://github.com/user-attachments/assets/23087c93-2e7b-4d23-8755-772d61ef66fe">

**Comment by bagder** [comment]
Ack, it also goes wrong with non-json output.

**Comment by schpet** [comment]
thanks for fixing this up, looking forward to the next release!

**Comment by bagder** [comment]
I'm a little busy with this curl release until Wednesday, but I'll get a trurl release done after that.
