### ISSUE TITLE
Differences in COPYING and other files' boilerplate license text

### ISSUE THREAD

**Issue by charles2910** [curl/trurl#365]
Hi,

I saw that trurl's COPYING file has `Copyright (c) 2023 - 2024, Daniel Stenberg, <daniel@haxx.se>` while other files's boilerplate has `Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.`. Does the project intend to have them differently or is something that's just was updated in one place but not the other?

**Comment by bagder** [comment]
You mean the `et al` difference or the year range?

The year range is meant to only be in the COPYING. The `et al` part I'm not sure.

**Comment by charles2910** [comment]
Hi,

> the et al difference

I should have clarified that was the et al part, my bad. I'm not sure how strict it should be maintaining the same name for the copyright holder (I'm not a layer famous disclaimer here :-) but would be nice for distributors (aka distro packagers) to be the same.
