### ISSUE TITLE
canonised url ?

### ISSUE THREAD

**Issue by JimFuller-RedHat** [curl/trurl#371]
Is there concept of canonised url ? for example url param sorting ?

**Comment by bagder** [comment]
There is `--sort-query`, using that URLs should be almost "canonised". I am a bit hesitant to call them that or use that phrase, as I there might still be ways that they are not.

**Comment by JimFuller-RedHat** [comment]
re canonisation - well there is the safe set ... encoding/decoding as well to consider

**Comment by bagder** [comment]
trurl decodes/encodes (most) fields already
