### ISSUE TITLE
Loop over multiple --sets

### ISSUE THREAD

**Issue by jacobmealey** [curl/trurl#40]
I'm not sure what it would look like but it would be helpful to generate a range of URLs for something like the port. I was thinking it could have a syntax similar to below but there is most certainly a better way! 
`./trurl --url google.com --set port=[1000-1005]`

or if it's something that would be a string instead of numbers it could take a list like:
`./trurl --url google.com --set host=[google.co.uk, google.co.nz]`

**Comment by bagder** [comment]
Maybe we could have a separate option for that. Like `--iterate`  or something that can accept ranges and lists like proposed here.

**Comment by jacobmealey** [comment]
That makes sense, and would probably require less rewriting of existing stuff. Were you thinking it would work something like: 

`trurl --url something.com --iterate hosts=[another.com, something.co.uk]` ? 

It probably wouldn't need the brackets, not sure why I am so fixated on them. It could probably be something like the following, but that may make parsing a little trickier:
`trurl --url something.com --iterate hosts=another.com, something.co.uk ports=80,443,8080`

**Comment by bagder** [comment]
Something like that, yes. It might make more sense to use spaces as separators rather than comma though, simply because space cannot legally be part of any component.

And maybe one "loop" per `--iterate` option?

~~~
$  trurl --url something.com --iterate "host=another.com something.co.uk" --iterate "port=80 443 8080"

**Comment by jacobmealey** [comment]
Excellent. I can start working on it this evening.

**Comment by Earnestly** [comment]
Would it be unreasonable to just issue the command multiple times instead?

**Comment by Earnestly** [comment]
That's fair.  Another possible design would be similar to curl's `-K config` which accepts a `key=value` format much like `-s, --set` does here.  E.g.

```
url=something.com host=another.com port=80
url=something.com host=another.com port=443
url=something.com host=another.com port=8080
url=something.com host=something.co.uk port=80
url=something.com host=something.co.uk port=443
url=something.com host=something.co.uk port=8080
```

Which can be generated with something like:

```
printf '%s\n' 'url=something.com host='{another.com,something.co.uk}' port='{80,443,8080}
```

(Although this use of brace expansion isn't POSIX sh yet: https://austingroupbugs.net/view.php?id=1193#c3995)

**Comment by jacobmealey** [comment]
Folks, I just wanted to share a quick update. I have parsing of the `--iterate` flag working and it generates urls if only a single variable is being iterated. for example `trurl --url something.com --iterate "ports=80 443 8080"` produces:
```
http://something.com:8080/
http://something.com:80/
http://something.com:443/
```
and `./trurl --url url-to-nas.com --iterate schemes="sftp ftps smb" ` generates

```
smb://url-to-nas.com/
sftp://url-to-nas.com/
ftps://url-to-nas.com/
```

I am having some trouble getting multiple to work together but I think I am just overthinking it all and I'm just gonna call it a night and try again in the morning.
