### ISSUE TITLE
Output JSON

### ISSUE THREAD

**Issue by d-gagne** [curl/trurl#44]
To hook into other tooling, or just to give all the things in one command, it would be handy to have `trurl --url <url> --json` so you can pipe to jq or logging, or whatever else.

For example 

```

$ trurl --url "https://curl.se/user?id=foo" --json
{
  "host": "curl.se",
  "scheme": "https",
  "port": "443",
  "path": "user",
  "query": [ { "id": "foo" } ],
}

```

**Comment by bagder** [comment]
Makes perfect sense!
