### ISSUE TITLE
multiple URL JSON output?

### ISSUE THREAD

**Issue by bagder** [curl/trurl#49]
How is the JSON format supposed to look like when trurl outputs multiple objects?

Right now it looks like this when given 4 URLs:
~~~
$ cat urls.txt | ./trurl --json -f -
{
  "url": "http://localhost/",
  "scheme": "http",
  "host": "localhost",
  "port": "80",
  "path": "/",
}
{
  "url": "http://haxx.se/",
  "scheme": "http",
  "host": "haxx.se",
  "port": "80",
  "path": "/",
}
{
  "url": "https://curl.se/",
  "scheme": "https",
  "host": "curl.se",
  "port": "443",
  "path": "/",
}
{
  "url": "http://curl.haxx.se/",
  "scheme": "http",
  "host": "curl.haxx.se",
  "port": "80",
  "path": "/",
}

**Comment by paulroub** [comment]
Good question - as the code is written, it would take some gymnastics to make it behave differently for one URL (where a single `{ ... }` would do) vs multiple (where you'd want an array for things to be parseable by anything else). 

There's probably an advantage to always outputting an array, even if it's a single URL -- consistent parsing, consistent examples, etc.  

So I'd suggest:

```json
[
  {
    "url": "http://localhost/",
    "scheme": "http",
    "host": "localhost",
    "port": "80",
    "path": "/"
  }
  {
    "url": "http://haxx.se/",
    "scheme": "http",
    "host": "haxx.se",
    "port": "80",
    "path": "/"
  }
  {
    "url": "https://curl.se/",
    "scheme": "https",
    "host": "curl.se",
    "port": "443",
    "path": "/"
  }
  {
    "url": "http://curl.haxx.se/",
    "scheme": "http",
    "host": "curl.haxx.se",
    "port": "80",
    "path": "/"
  }
]
```

(dropping the trailing commas, which are not valid JSON)

**Comment by bagder** [comment]
Thanks, I will poke the code accordingly!
