### ISSUE TITLE
Getting the punycode version

### ISSUE THREAD

**Issue by bagder** [curl/trurl#64]
Due to to [how crazy IDN is](https://daniel.haxx.se/blog/2022/12/14/idn-is-crazy/) the only way to be able to get a canonical version of a URL with IDN is to convert it to its punycode version, which I figure is a valid reason for trurl to offer this feature: extract the host as punycoded or show the entire URL with the host name punycoded.

But how to expose this power to the CLI ?

My initial thinking is to use another symbol for the `--get` variables. We already do `{:var}` for *not* URL decoding, and we could use something else than colon to ask for the punycoded version. Maybe '*' ?  Then you can ask for both the plain name and the punycoded one in the same command line: `--get '{host} {*host}'`

Thoughts? Better ideas?

**Comment by bagder** [comment]
Good point about the asterisk. Let's avoid that then. Maybe go more verbose: `{puny:host}` ?

**Comment by adamhotep** [comment]
> Maybe go more verbose: `{puny:host}` ?

I believe punycode only applies to hosts, so maybe just `{puny}` is sufficient, unless you're looking for a general conversion, in which case consider syntax that would be consistent with a percent-encoding/decoding system.

**Comment by bagder** [comment]
You can also output `{url}` and it could be asked to have the host name punycoded. So there are two components.

**Comment by paulroub** [comment]
> Good point about the asterisk. Let's avoid that then. Maybe go more verbose: `{puny:host}` ?

I like the verbose approach.

**Comment by jacobmealey** [comment]
I like the verbose approach, but I think it only makes sense if all non-standard/odd url things are handled with the same approach.
