### ISSUE TITLE
Get and set the origin

### ISSUE THREAD

**Issue by lgarron** [curl/trurl#66]
The origin is the foundational concept in web security, [defined as the combination of scheme, host, and port](https://www.rfc-editor.org/rfc/rfc6454).

I'd love to have a way to either get the origin or a URL, or replace it. This is not only a convenience for calculating the main browser security boundary of a URL, but it could also avoid bugs because it's easy to forget about the port and write incorrect code otherwise.

For example:

```
> trurl --get "{origin}" --url https://twizzle:twizzle@alpha.twizzle.net/deploy-versions/
https://alpha.twizzle.net
```

```
> trurl --set "origin=https://example.com" --url localhost:8000/app/?foo=bar
https://example.com/app/?foo=bar
```

That said, the origin is a combination of other URL parts, so I'm not sure it should have the same syntax.

**Comment by bagder** [comment]
I would be open for adding support for this "special" component. I suspect we might think of more additional ones as we moving along.

**Comment by bagder** [comment]
Since origin is created by three component already available for get and set, I'm going to defer this idea/work until a later date.

**Comment by lgarron** [comment]
> Since origin is created by three component already available for get and set, I'm going to defer this idea/work until a later date.

Sounds sensible! I've made myself convenience functions for now:

```fish
# `fish` functions

function trurl-set-origin
  if test (count $argv) -lt 2
    echo "Usage: trurl-set-origin <URL> <ORIGIN>"
    echo "Example: trurl-set-origin \"localhost:8000/app/?foo=bar\" \"https://example.com\""
    return 1
  end
  set SCHEME (trurl --get "{scheme}" $argv[2])
  set HOST (trurl --get "{host}" $argv[2])
  set PORT (trurl --get "{port}" $argv[2])
  trurl --set scheme=$SCHEME --set host=$HOST --set port=$PORT $argv[1]
end

function trurl-get-origin
  if test (count $argv) -lt 1
    echo "Usage: trurl-set-origin <URL>"
    echo "Example: trurl-set-origin \"localhost:8000/app/?foo=bar\""
    return 1
  end
  trurl-set-origin example.com $argv[1]
end
```
