### ISSUE TITLE
Python test script

### ISSUE THREAD

**Issue by sevehub** [curl/trurl#74]
Have a look at https://github.com/sevehub/trurl, JSON data (test.json) and the script (test.py) are separated. It also shows the return codes.

Let me know if you prefer this solution or if you are happier with the existing Perl scripts.

**Comment by havbon** [comment]
This sounds like a more convenient solution in my opinion.
Although i have some issues with your code, this is the output i get when running the tests via windows powershell:
![image](https://user-images.githubusercontent.com/46850782/230207089-c0964931-c10b-40ca-a585-353809a12c91.png)

Any ideas?

**Comment by sevehub** [comment]
When you run the command without arguments you get this return code and stderr. Same with other shells (command prompt, bash, ...).

**Comment by bagder** [comment]
> When you run the command without arguments you get this return code and stderr

But he ran the test python script. Why would that say error?

**Comment by sevehub** [comment]
It can be replaced with a different message.
Haven't recompiled the executable in a while, with the version that I am using when I run 'trurl.exe' without arguments I get:
```
C:\Users\Seve\>trurl.exe
not enough input for a URL (trurl -h for help)
```
with 7 as the return code.

It corresponds to the empty test URL "|".
The test script just shows the stderr output, believed was something useful to have.

**Comment by bagder** [comment]
Sure, but why does it show stderr from the tests? Either it should verify that the stderr output is as expected or it should hide it I think.

**Comment by bagder** [comment]
My biggest reason for hesitating to merge this is that this is code and infrastructure that I feel very unfamiliar with, so it will add a hurdle for me personally to develop this.

**Comment by sevehub** [comment]
I completely understand. I can either suggest creating an ad-hoc branch (call it something like dev-test) and see how it develops or close this issue and keep the existing test. 
Python should be more popular than Perl, and hopefully, there will be more commits from other contributors. This should also reduce your workload.

**Comment by sevehub** [comment]
I haven't an answer yet. Probably the best option, it's to verify if the return code is the expected one.

**Comment by havbon** [comment]
I had a few issues when trying to get sevehubs script to work, so I attempted to make my own version. Using his "test.json" file

![image](https://user-images.githubusercontent.com/46850782/230665342-ab7e256e-81fe-40ec-84ba-14f007ced385.png)


I understand the hesitation @bagder. I've tried my best to make the code as readable as possible, have a look and let me know what you think. https://github.com/havbon/trurl/tree/pythonTests

the script is developed in python 3.10 on windows, tested in powershell. let me know if it doesn't work for you, or you have any other questions.

**Comment by bagder** [comment]
Things I would like the test suite able to do going forward:

 - run the tests with valgrind (if available) on/off
 - run just a specific test case
 - verify the exit code (to better test errors))
 - verify stderr output (also to test errors and error messages proper)

While at the same time keeping the ease of creating new test cases.

**Comment by havbon** [comment]
I added the following features:
- run just a specific test case
- verify the exit code (to better test errors)
- verify stderr output (also to test errors and error messages proper)

You can see the code here: https://github.com/havbon/trurl/tree/pythonTests

In order to run specific cases simply run `test.py index,index,index` (comma sep no spaces)
I planted a few issues for testing purposes.

The code now uses a class called TestCase which is used to keep track of variables and results in each test, this makes the code scalable. I don't really know how to implement valgrind as i run windows, but I will look around for workarounds and alternatives.

**Comment by bagder** [comment]
I like how this looks.

Can you convert the entire existing test.pl test suite to this format and make a pull-request out of this? It will give it more attention before we merge. The valgrind part I'm sure we can fix after an initial merge as well. It's not complicated.

**Comment by sevehub** [comment]
I am not so sure it's a good idea to include the stderr output inside the test file. I will require substantial work to keep the test and the trurl.c file aligned.

**Comment by bagder** [comment]
You may be right. When it comes to errors, the more important part is the exit code so maybe we should start with verifying that only and save stderr checking for later.
