### ISSUE TITLE
Install on ubuntu

### ISSUE THREAD

**Issue by Epic-R-R** [curl/trurl#89]
When running the `make` command for installing trurl
`
cc  -W -Wall -pedantic -g   -c -o trurl.o trurl.c
trurl.c:29:10: fatal error: curl/curl.h: No such file or directory
   29 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: trurl.o] Error 1
`

**Comment by bagder** [comment]
This looks like you did not install the libcurl dev package, mentioned in the README.
