### ISSUE TITLE
url-encoding

### ISSUE THREAD

**Issue by bagder** [curl/trurl#9]
Offer a way to URL encode input similar to curl's `--data-urlencode` and `--url-query`

**Comment by bagder** [comment]
Would it be too subtle to use a different assignment symbol for `--set` (and `--get`) to do URL encode/decode?

`--set path=data` exits for getting the data already encoded,

We could add

`--set path:data` for URL encoding the data. Alternatively we spell it out like `--set path:encode=data`.

For URL decoding in the `--get` case, we could extend the `{variable}` syntax to specify if you want URL decoded results. Maybe like `[path]` or `{path:decode}`.

**Comment by bagder** [comment]
It has also been proposed maybe we should default to do the encoding and provide "raw" as an additional option.

**Comment by Earnestly** [comment]
In my experience every example of `curl -d` and `--data` I have encountered in the wild doesn't percent encode the parameters (or assumes they already are) and in those cases can be fixed by using `--data-urlencode`.  I agree that encoding by default would be a safer bet in most real world cases.
