### ISSUE TITLE
split the query in JSON

### ISSUE THREAD

**Issue by bagder** [curl/trurl#90]
The #44 proposal for JSON output shows the query component being split up in sub-components. That's was not implemented in the first json take but is probably still a good idea! Probably *in addition* to the full query. Something like:
~~~
$ trurl --url "https://curl.se/user?id=foo&size=44" --json
{
  "host": "curl.se",
  "scheme": "https",
  "port": "443",
  "path": "user",
  "query": "id=foo&size=44",
  "q": {
    "id": "foo",
    "size": "44"
  } 
}
~~~

Leaves a few questions: what if there are many `id` or `size` ? What if there is no `=` at all?

**Comment by xfgusta** [comment]
> Leaves a few questions: what if there are many `id` or `size` ?

What about creating an array that preserves the order of the query parameters?

**`id=foo&id=bar&size=44`**

```json
{
  "q": {
    "id": ["foo", "bar"],
    "size": "44"
  }
}
``` 

> What if there is no = at all?

I think it's best to represent it with an empty string.

**`id=foo&size`**

```json
{
  "q": {
    "id": "foo",
    "size": ""
  }
}
```

**Comment by bagder** [comment]
Makes perfect sense!

Since I merged 9a7cc371f6c, this should be fairly straight forward to implement.

**Comment by bagder** [comment]
can we do something nicer than `"q"` there?

**Comment by bagder** [comment]
#100 is a first take, not quite there yet.

**Comment by xfgusta** [comment]
> can we do something nicer than `"q"` there?

I think we could use `params`:

```
$ trurl --url "https://curl.se/user?id=foo&size=44" --json
{
  "host": "curl.se",
  "scheme": "https",
  "port": "443",
  "path": "user",
  "query": "id=foo&size=44",
  "params": {
    "id": "foo",
    "size": "44"
  } 
}
```

Note that `params` is used in the JavaScript [`URLSearchParams` API](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

**Comment by bagder** [comment]
Ok, "params" it is.
