### ISSUE TITLE
Handling mailto: URLs

### ISSUE THREAD

**Issue by AMR692** [curl/trurl#97]
This doesn't seem to handle mailto: URLs. It prepends "http://" to the input and treats it as a web link.

```
$ trurl "mailto:jdoe@example.com?subject=foo?body=bar" --json
[
  {
    "url": "http://mailto:jdoe@example.com/?subject=foo?body=bar",
    "scheme": "http",
    "user": "mailto",
    "password": "jdoe",
    "host": "example.com",
    "port": "80",
    "path": "/",
    "query": "subject=foo?body=bar"
  }
]
```

**Comment by bagder** [comment]
That's indeed correct and a current limitation. The libcurl URL parser is limited to the hierarchical file system like ones (`://` basically).

**Comment by oalders** [comment]
Related to this, it would be great to be able to parse Git's SSH URLs: `git@github.com:curl/trurl.git`
